name: "skilltree-backend"

services:
  database:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: skilltree
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 9000:9000

volumes:
  mysql-data:
