version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: skilltree
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 9000:8080

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/skilltree
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MYSQL_HOST: db
      DB_NAME: skilltree
      MYSQL_DB_USERNAME: testuser
      MYSQL_DB_PASSWORD: testpassword
      DB_DDL_POLICY: update
      API_V1_PREFIX: /api/v1
      SPRING_DATASOURCE_VERSION: 8.1.0

volumes:
  mysql-data:
