version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'testpassword'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
